version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "HttpTriggerLambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-10yogma91int1"
s3_prefix = "HttpTriggerLambda"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppBucketName=\"bucket-csv-files-20202014\" TopicURI=\"notification-csv-error\" DynamoDbTableName=\"csv_position_table\""

