AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  HttpHandleTriggerLambda

Parameters:
  AppBucketName: 
    Type: String
    Description: "REQUIRED: Unique S3 bucket name to use for the app."
  TopicURI: 
    Type: String
    Description: "Topic name of SNS"
  DynamoDbTableName:
    Type: String
    Description: "table name of dynamoDb for save csv data"
Resources:
  HttpHandleTriggerLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/http-handle.httpHandle
      Runtime: nodejs12.x 
      Environment:
        Variables:
          CSV_ERROR_TOPIC: !Ref SNSTopic
          DYNAMODB_TABLE: !Ref DynamoDbTableName
      MemorySize: 128
      Timeout: 60
      Policies:
        - AWSLambdaExecute
        - Statement:
          - Sid: DynamoDbPutItemPolicy
            Effect: Allow
            Resource: !GetAtt DynamoDbTable.Arn
            Action: 
              - dynamodb:PutItem
          - Sid: SNSPublishPolicy
            Effect: Allow
            Resource: !Ref SNSTopic
            Action: 
              - sns:Publish
  apiGateway:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: "my-api"
      Description: "My API"
  apiGatewayRootMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: "NONE"
      HttpMethod: "POST"
      Integration:
        IntegrationHttpMethod: "POST"
        Type: "AWS_PROXY"
        TimeoutInMillis: 29000
        Uri: !Sub
          - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations"
          - lambdaArn: !GetAtt "HttpHandleTriggerLambda.Arn"
      ResourceId: !GetAtt "apiGateway.RootResourceId"
      RestApiId: !Ref apiGateway
  apiGatewayDeployment:
    Type: "AWS::ApiGateway::Deployment"
    DependsOn:
      - "apiGatewayRootMethod"
    Properties:
      RestApiId: !Ref apiGateway
      StageName: "test"
  lambdaApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt "HttpHandleTriggerLambda.Arn"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${apiGateway}/*/POST/"

  CSVBucket: 
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AppBucketName
  DynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "position_guid"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "position_guid"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Ref DynamoDbTableName
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: !Ref TopicURI